version: '3.1'
services:
    cassandra:
      image: stpic270/bd-secl-cassandra
      volumes:
        - cassandra_config:/config

      command: bash -c "echo '\n' >> config/cassandra_config.txt && ip -4 -o address >> config/cassandra_config.txt"



    model:
       image: stpic270/bd-secl-d:latest
       ports:
           - 77:70
       volumes:
           - cassandra_config:/app/test
       command: bash -c "python src/preprocess.py && python src/train.py -m BNB && python src/predict.py -m BNB -t func && python use_cassandra.py && coverage run src/unit_tests/test_preprocess.py && coverage run -a src/unit_tests/test_training.py && coverage report -m"
    
volumes:
    cassandra_config: