pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS=credentials('sikasi')
        LC_ALL = "en_US.UTF-8"
        LANG    = "en_US.UTF-8"
        LANGUAGE = "en_US.UTF-8"
        SLEEP_TIME_IN_SECONDS1 = 420
    }

options {
        timestamps()
        skipDefaultCheckout(true)
	}
    stages {

        stage('Login'){
            steps{
                //withCredentials([usernamePassword(credentialsId: 'mle-template', passwordVariable: 'DOCKER_REGISTRY_PWD', usernameVariable: 'DOCKER_REGISTRY_USER')]){
                //bat 'chcp 65001 && echo %DOCKER_REGISTRY_PWD% | docker login -u %DOCKER_REGISTRY_USER% --password-stdin'}
                sh 'echo $DOCKERHUB_CREDS_PSW | docker login -u $DOCKERHUB_CREDS_USR --password-stdin'
//                 sh 'docker login -u %DOCKERHUB_CREDS_USR% -p %DOCKERHUB_CREDS_PSW%'
                }
            }

        stage('Pull image'){
            steps{
                sh '''
                    docker pull stpic270/bd-thl-d:latest
                    docker pull stpic270/bd-secl-cassandra:latest
                '''
            }
        }

        stage('Run container'){
            steps{

                sh 'docker start big_data_third_lab-model-1'
                
                echo "Waiting 30 seconds for entrypoint script"
                sleep 30
                
                sh  '''
                    docker start big_data_third_lab-cassandra-1
                    docker exec -t big_data_third_lab-cassandra-1 bash -c "echo '\n' >> config/cassandra_ip.txt && ip -4 -o address >> config/cassandra_ip.txt"
                    docker exec -t big_data_third_lab-model-1 bash -c "scripts/cassandra.sh"
                    docker stop big_data_third_lab-model-1
                    '''
                }
        }
	}

    post {
        always {
            sh 'docker stop big_data_third_lab-cassandra-1 && docker stop big_data_third_lab-model-1 && docker logout'
        }
    }
}
